default_language_version:
  python: python3.10
default_stages: [commit]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: fix-encoding-pragma
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.942
  hooks:
  - id: mypy
    args: ['--ignore-missing-imports', '--disable-error-code', 'name-defined']
- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    entry: pflake8
    additional_dependencies:
    - flake8-annotations
    - flake8-bandit
    - flake8-bugbear
    - flake8-comprehensions
    - flake8-docstrings
    - flake8-pytest-style
    - flake8-spellcheck
    - darglint
    - pyproject-flake8
