name: Setup Python Semantic Release
description: 'Prepare Python Semantic Release'

inputs:
  gh_token:
    description: "Github token for validating uploads."
    required: True
  pypi_token:
    description: "PyPI token for validating uploads."
    required: True
  cache_number:
    description: "A manually specified cache number. Useful for triggering new caches."
    required: True
    default: 0
  poetry_version:
    description: "Which poetry version to use."
    required: True
    default: 1.8.5
  psr_version:
    description: "Which python semantic release version to use."
    required: True
    default: 9.21.0

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Cache Pip
      uses: actions/cache@v4
      with:
        path: ~/.pip
        key:
          pip${{ inputs.cache_number }}-PT${{ inputs.poetry_version }}-PRS${{ inputs.psr_version }}
    - name: Get Dependencies
      shell: bash
      run: |
        pip install poetry==${{ inputs.poetry_version }} python-semantic-release==${{ inputs.psr_version }}
    - name: Configure git
      shell: bash
      run: |
        git config --global user.name 'rbpatt2019'
        git config --global user.email 'rbpatt2019@users.noreply.github.com'
    - name: Python Semantic Release
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
        POETRY_PYPI_TOKEN_PYPI: ${{ inputs.pypi_token }}
        PYPI_TOKEN: ${{ inputs.pypi_token }}
      shell: bash
      run: |
        semantic-release -v version
        poetry build
        poetry publish -vv
